### ISSUE TITLE
[ISSUE][loading-images-to-assets-folder]

### ISSUE THREAD

**Issue by Yashkarwa460** [CodeKul/weekend-angular-10.30-11.30-15-dec-2018#3]
Do we need to use any command to insert image in asset folder and the give its location to anchor tag??? OR just copy the image to assets folder and access it in  anchor tag using its locations url.???

**Comment by aniruddhha** [comment]
Just copy the images to assets folder. And use canonical url pattern e.g. `<a href="../assets/my.png">hii</a>`

**Comment by aniruddhha** [comment]
Invalid format for asking question.

**Comment by Yashkarwa460** [comment]
Thanks alot sir it worked..
