### ISSUE TITLE
[ISSUE][issue occure in running project]

### ISSUE THREAD

**Issue by ghost** [CodeKul/weekend-angular-10.30-11.30-15-dec-2018#5]
C:\angular\my work 1st>npm start
npm ERR! path C:\angular\my work 1st\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\angular\my work 1st\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MY\AppData\Roaming\npm-cache\_logs\2019-01-10T04_34_18_918Z-debug.log

C:\angular\my work 1st>npm ERR! path C:\angular\my work 1st\package.json

**Comment by aniruddhha** [comment]
This error comes only because you are trying to run ng serve twice on same port. Do run your project again and again. For windows kill node service

**Comment by aniruddhha** [comment]
improper question format.
